config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => "user/registrations",
    :sessions => 'user/sessions'
  }

  get '/search' => 'search#index'
  get '/search/list' => 'search#list'

  get '/mypage' => 'mypage#my_post'
  get '/mypage/new_news/:users_id' => 'mypage#new_news'
  get '/mypage/bookmark/:users_id' => 'mypage#bookmark'
  get '/mypage/setting/:users_id' => 'mypage#setting'

  resources :posts do
      resources :comments, only: [:create]
    end
  resources :comments, only: [:edit, :update, :destroy]

  resources :posts, except: [:show] do
     post "/bookmark", to: "mypage#bookmark_toggle"
  end

  post '/posts/:id/comment_create' => 'posts#comment_create'
  get '/' => 'posts#index'

  namespace :api do
    namespace :v1 do
      resources :posts
      get '/search', :to => 'search#index'
      get '/search/list', :to => 'search#list'
      get '/mypage' => 'mypage#my_post'
      get '/mypage/bookmark/:users_id' => 'mypage#bookmark'
      get '/mypage/setting/:users_id' => 'mypage#setting'
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        post "/sign_up", :to => 'registrations#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  has_many :bookmarks

  def self.search(query)
    where("title LIKE ? OR content LIKE ? OR hashtag LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  before_action :authenticate_user_from_api!, only: :show
  before_action :set_post, only: [:show, :update, :edit, :destroy]

  #
  swagger_controller :posts, "test"
  swagger_api :index do
    summary "Fetches all User items"
    notes "This lists all the active users"
    param :query, :page, :integer, :optional, "Page number"
    param :path, :nested_id, :integer, :optional, "Team Id"
    response :unauthorized
    response :not_acceptable, "The request you made is not acceptable"
    response :requested_range_not_satisfiable
  end
  swagger_api :show do
    summary "Fetches a single User item"
    param :path, :id, :integer, :optional, "User Id"
    response :ok, "Success", :User
    response :unauthorized
    response :not_acceptable
    response :not_found
  end
  #

  def index
    @posts = Post.all
  end


  def show
    @comments = Comment.where("post_id = ?", @post.id)
    @comment = Comment.new
  end

  # view 없는 것
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        render :show, status: :created, location: @post
      else
        render json: @post.errors, status: :unprocessable_entity
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.json { render :show, status: :ok, location: @post }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :hashtag, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_post, only: [:show, :update, :edit, :destroy]

  # view 있는 것
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit

  end

  def show
    @user = User.find(@post.user_id)
    @comments = Comment.where("post_id = ?",@post.id)
    @comment = Comment.new
  end

  # view 없는 것

  def create
    @post = Post.new(post_params)
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status:
            :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status:
            :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  def set_post
    @post = Post.find(params[:id])

  end

  def post_params
    params.require(:post).permit(:title, :content, :hashtag, :user_id)
  end

end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
<div class="field">
  <%= f.label :title %> <br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :content %> <br>
  <%= f.text_area :content %>
</div>
<div class="field">
  <%= f.label :hashtag %> <br>
  <%= f.text_area :hashtag %>
</div>
<<<<<<< HEAD
  <%= f.hidden_field :user_id,value: current_user.id %>
=======

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

>>>>>>> add_front2
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>게시판</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/assets/search.css">
    <link rel="stylesheet" type="text/css" href="/assets/main.css">
    <link rel="stylesheet" type="text/css" href="/assets/style_common.css">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <title>TMI_Example</title>
</head>
<body>
<nav>
  <div class="nav-section">
    <%= link_to "/" do %>
    <%= image_tag ("logo1.png"), class: "logo-img" %>
    <% end%>
    <div class="nav-upper-button-wrap">
          <button class="write" onclick="location.href='/posts/new'">
            <%= image_tag ( "write.png" ) %>
          </button>
          <button onclick="location.href='/mypage'">
            <%= image_tag ( "user.png" ) %>
          </button>
      </div>


        <div class="content-reply-input">
          <div class="icon_search">
            <button class="search-btn" onclick = "location.href ='/search'">
            <%= image_tag ( "search.png" ) , :style=>"width:20px" %>

          </div>
        </div>

  </div>

</nav>



<div class="content-wrapper">
    <!--SINGLE ELEMENT-->
  <% @posts.each do |post| %>
    <a href="/posts/<%=post.id%>" style="text-decoration: none;">
      <div class="content-element">
          <div class="content-preview">
              <div class="content-preview-title">
                <%= post.title %>
                  <!-- 강남역 인근 <span class="search-text">주말 주차 장소</span> 추천 -->
              </div>
              <div class="content-preview-text">
                <%= post.content %>
              </div>
              <div class="content-preview-timestamp"><%= post.user.nickname %> <%= post.created_at.strftime("%m.%d") %></div>
          </div>
          <div class="content-hashtag"><%=post.hashtag %></div>
          <div class="content-reply">
              <i class="fa fa-clipboard-list"></i>&nbsp; <%= post.comments.count %>
          </div>
      </div>
    </a>
  <% end %>
</div>

</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../assets/css/style_common.css">

        <link rel="stylesheet" type="text/css" href="../assets/css/write.css">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <title>TMI_Example</title>
</head>
<body>
  <nav>
      <div class="nav-upper-section">
      <%= link_to "/" do %>
        <%=image_tag ("logo1.png"), class: "logo-img" %>
        <% end %>
          <div class="nav-upper-button-wrap">
              <button class="write" onclick="location.href='/posts/new'">
                  <%= image_tag ("write.png") %>
              </button>
              <button onclick = "location.href = '/mypage'">
                  <%= image_tag ("user.png") %>
              </button>
          </div>
      </div>

  </nav>

<div class="content-wrapper">

    <div class="write-wrapper">
    <%= form_for(@post) do |f| %>
            <div class="write-title">
            <%= f.text_field :title, :class => "title", placeholder: "제목" %>
            </div>

            <div class="write-content">
            <%= f.text_area :content, :class => "content", placeholder: "본문" %>
        </div>

        <div class="write-tag">
            <%= f.text_area :hashtag, :class => "tag", placeholder: "태그" %>
        </div>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <button class="submit" type="submit">+ 게시하기</button>
    </div>
<% end %>
</div>

</body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/assets/postView.css">
    <link rel="stylesheet" type="text/css" href="/assets/style_common.css">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <title>TMI_Example</title>
</head>
<body>
<nav>
    <div class="nav-upper-section">
        <button onclick="location.href='/posts'" class="back-button">
          <%= image_tag ( "chevron_left.png" ) , :class=>"back-img"%>
        </button>
    </div>
</nav>
<div class="contenta-wrapper">
    <!--SINGLE ELEMENT-->
    <div class="content-element show-wrap">
        <div class="content-preview">
            <div class="content-title">
              <%= @post.title %>
            </div>
            <div class="content-timestamp"><%= @user.nickname %> <%= @post.created_at.strftime("%m.%d") %></div>
            <div class="content-text">
              <%= @post.content %>
            </div>
        </div>
        <div class="content-hashtag"> <%= @post.hashtag %> </div>
        <div class="content-reply">
            <i class="fa fa-clipboard-list"></i>&nbsp; <%= @post.comments.count %>
            <% if current_user.is_Bookmark?(@post) %>
            <%= link_to image_tag("bookmark_yes.png", class:"bookmark-img-link"), post_bookmark_path(@post), method: "post", class:"like-none" %>
            <% else %>
            <%= link_to image_tag("bookmark_no.png", class:"bookmark-img-link"), post_bookmark_path(@post), method: "post", class:"like-yes" %>
            <% end %>

        </div>
        <% @comments.each do |c| %>
        <div class="content-reply-list">
            <div class="content-reply-name">
                <%= c.user.nickname %>
            </div>
            <div class="content-reply-text">
              <%= c.content %>
            </div>
        </div>
        <% end %>
        <div class="content-reply-write">

            <div class="content-reply-write-name">

            </div>

          <div class="reply-input-div">
              <%= form_for Comment.new, url: post_comments_path(@post.id) do |f| %>
                <%= f.text_field :content, placeholder:"댓글을 입력하세요"%>
                <%= f.hidden_field :post_id, value: @post.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <button class="submit-reply" type="submit">저장</button>
              <% end %>
          </div>
        </div>
    </div>

</div>

</body>
<!-- <script src="../assets/javascripts/routeByButton.js"></script> -->

</html>